# Copyright (c) 2018-2022 The MobileCoin Foundation
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mobilecoind.fullname" . }}-supervisor-daemon-config
  labels:
    {{- include "mobilecoind.labels" . | nindent 4 }}
data:
  supervisor.conf: |
    [supervisord]
    nodaemon=true
