name: 👾 Mobilecoin Dev Environment Info 👾
description: Display info for development namespace.

outputs:
  branch:
    description: "normalized branch name"
    value: ${{ steps.meta.outputs.branch }}
  namespace:
    description: "namespace based off normalized branch name"
    value: ${{ steps.meta.outputs.namespace }}
  tag:
    description: "artifact semver tag based off of branch patterns"
    value: ${{ steps.meta.outputs.tag }}

runs:
  using: composite
  steps:
  - name: Checkout
    uses: actions/checkout@v3

  - name: Generate version metadata
    id: meta
    shell: bash
    run: |
      .internal-ci/util/metadata.sh

  - name: 👾 Print Environment Details 👾
    shell: bash
    env:
      NAMESPACE: ${{ steps.meta.outputs.namespace }}
      VERSION: ${{ steps.meta.outputs.tag }}
    run: |
      .internal-ci/util/print_details.sh
